/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab5;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException, InvocationTargetException, NoSuchMethodException, ClassNotFoundException, InstantiationException, IllegalAccessException {

        SomeBean sb = (SomeBean) (new Injector()).inject(new SomeBean(), "src/main/recources/tmp.properties");
        sb.foo();


    }
}
