/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab5;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        SomeBean sb = (SomeBean) (new Injector()).inject(new SomeBean(), "random.properties");
        //sb.foo();


    }
}
