/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab1;

import org.junit.Test;
import static org.junit.Assert.*;

public class MyContainerTest {
    @Test public void testContainer() {
        MyContainer<Integer> classUnderTest = new MyContainer<Integer>(5);
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
