/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab4;

import java.util.HashMap;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        DictionaryFabric dictionaryFabric = new ManDictionaryFacric();

        MyCSVReader csvReader = new MyCSVReader("foreign_names.csv",';', dictionaryFabric);

        List csvContent = csvReader.readCSV();
        HashMap qwe = (HashMap) csvContent.get(0);
        Division div = (Division) qwe.get("Division");

        System.out.println(csvContent);
        System.out.println(div.getLetter());

    }
}
