/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab4;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        MyCSVReader mrd = new MyCSVReader(';');

        List qwe = mrd.readCSV("foreign_names.csv");

        System.out.println(qwe);
    }
}
