/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab4;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        DictionaryFabric dictionaryFabric = new ManFabric();

        MyCSVReader csvReader = new MyCSVReader("foreign_names.csv",';', dictionaryFabric);

        List csvContent = csvReader.readCSV();

        for (Object rows: csvContent)
             System.out.println(rows);

    }
}
