/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab1;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
	MyContainer<Integer> var = new MyContainer<Integer>(10);
	var.add(2);
        System.out.println(var.get(0));
    }
}
